version: '3.8'

services:
    app:
        build: .
        volumes:
            - .:/var/www
        expose:
            - "9000"

    web:
        image: nginx:alpine
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
